# Return a function that does nothing by default
def default_processor(player, event):
    pass

processors = {}
def get(id):
    try: return processors[id]
    except KeyError: return default_processor

def EventProcessor(id):
    def set_processor(processor):
        processors[id] = processor
        return processor
    return set_processor

# These do vary slightly between protocol versions
# eg. 110 is SHeroTalentTreeSelectedEvent
# and 110 is HeroTalentSelectedEvent
event_ids = {
    5: 'SUserFinishedLoadingSyncEvent',
    7: 'SUserOptionsEvent',
    9: 'SBankFileEvent',
    10: 'SBankSectionEvent',
    11: 'SBankKeyEvent',
    12: 'SBankValueEvent',
    13: 'SBankSignatureEvent',
    14: 'SCameraSaveEvent',
    21: 'SSaveGameEvent',
    22: 'SSaveGameDoneEvent',
    23: 'SLoadGameDoneEvent',
    25: 'SCommandManagerResetEvent',
    26: 'SGameCheatEvent',
    27: 'SCmdEvent',
    28: 'SSelectionDeltaEvent',
    29: 'SControlGroupUpdateEvent',
    30: 'SSelectionSyncCheckEvent',
    31: 'SResourceTradeEvent',
    32: 'STriggerChatMessageEvent',
    33: 'SAICommunicateEvent',
    34: 'SSetAbsoluteGameSpeedEvent',
    35: 'SAddAbsoluteGameSpeedEvent',
    36: 'STriggerPingEvent',
    37: 'SBroadcastCheatEvent',
    38: 'SAllianceEvent',
    39: 'SUnitClickEvent',
    40: 'SUnitHighlightEvent',
    41: 'STriggerReplySelectedEvent',
    43: 'SHijackReplayGameEvent',
    44: 'STriggerSkippedEvent',
    45: 'STriggerSoundLengthQueryEvent',
    46: 'STriggerSoundOffsetEvent',
    47: 'STriggerTransmissionOffsetEvent',
    48: 'STriggerTransmissionCompleteEvent',
    49: 'SCameraUpdateEvent',
    50: 'STriggerAbortMissionEvent',
    51: 'STriggerPurchaseMadeEvent',
    52: 'STriggerPurchaseExitEvent',
    53: 'STriggerPlanetMissionLaunchedEvent',
    54: 'STriggerPlanetPanelCanceledEvent',
    55: 'STriggerDialogControlEvent',
    56: 'STriggerSoundLengthSyncEvent',
    57: 'STriggerConversationSkippedEvent',
    58: 'STriggerMouseClickedEvent',
    59: 'STriggerMouseMovedEvent',
    60: 'SAchievementAwardedEvent',
    62: 'STriggerTargetModeUpdateEvent',
    63: 'STriggerPlanetPanelReplayEvent',
    64: 'STriggerSoundtrackDoneEvent',
    65: 'STriggerPlanetMissionSelectedEvent',
    66: 'STriggerKeyPressedEvent',
    67: 'STriggerMovieFunctionEvent',
    68: 'STriggerPlanetPanelBirthCompleteEvent',
    69: 'STriggerPlanetPanelDeathCompleteEvent',
    70: 'SResourceRequestEvent',
    71: 'SResourceRequestFulfillEvent',
    72: 'SResourceRequestCancelEvent',
    73: 'STriggerResearchPanelExitEvent',
    74: 'STriggerResearchPanelPurchaseEvent',
    75: 'STriggerResearchPanelSelectionChangedEvent',
    77: 'STriggerMercenaryPanelExitEvent',
    78: 'STriggerMercenaryPanelPurchaseEvent',
    79: 'STriggerMercenaryPanelSelectionChangedEvent',
    80: 'STriggerVictoryPanelExitEvent',
    81: 'STriggerBattleReportPanelExitEvent',
    82: 'STriggerBattleReportPanelPlayMissionEvent',
    83: 'STriggerBattleReportPanelPlaySceneEvent',
    84: 'STriggerBattleReportPanelSelectionChangedEvent',
    85: 'STriggerVictoryPanelPlayMissionAgainEvent',
    86: 'STriggerMovieStartedEvent',
    87: 'STriggerMovieFinishedEvent',
    88: 'SDecrementGameTimeRemainingEvent',
    89: 'STriggerPortraitLoadedEvent',
    90: 'STriggerCustomDialogDismissedEvent',
    91: 'STriggerGameMenuItemSelectedEvent',
    93: 'STriggerPurchasePanelSelectedPurchaseItemChangedEvent',
    94: 'STriggerPurchasePanelSelectedPurchaseCategoryChangedEvent',
    95: 'STriggerButtonPressedEvent',
    96: 'STriggerGameCreditsFinishedEvent',
    97: 'STriggerCutsceneBookmarkFiredEvent',
    98: 'STriggerCutsceneEndSceneFiredEvent',
    99: 'STriggerCutsceneConversationLineEvent',
    100: 'STriggerCutsceneConversationLineMissingEvent',
    101: 'SGameUserLeaveEvent',
    102: 'SGameUserJoinEvent',
    103: 'SCommandManagerStateEvent',
    104: 'SCommandManagerTargetPointEvent',
    105: 'SCommandManagerTargetUnitEvent',
    106: 'STriggerAnimLengthQueryByNameEvent',
    107: 'STriggerAnimLengthQueryByPropsEvent',
    108: 'STriggerAnimOffsetEvent',
    109: 'SCatalogModifyEvent',
    110: 'SHeroTalentSelectedEvent'
}
